### ISSUE TITLE
Problème d'affichage depuis mise à jours du JOCBundle

### ISSUE THREAD

**Issue by AxelANGENAULT** [AriiPortal/JOCBundle#1]
Bonjour,

J'ai mis quelques longues minutes à comprendre qu'il fallait déclarer les moteurs ...

Une fois les moteurs ajoutés nous avons accès à toutes les informations (ordres, lock, schedule ...), pas de problème de ce côté.

Par contre, en revenant sur la page de gestion des moteurs `/JOC/Réseau/Moteurs`,
le graph affiche les informations mais la liste n'affiche aucun moteur :
![joc](https://cloud.githubusercontent.com/assets/11269587/13918887/5afb4172-ef6a-11e5-943c-97feed07d80e.png)

Parfois j'ai le message suivant dans le coin supérieur droit :
![curl](https://cloud.githubusercontent.com/assets/11269587/13919222/6f203a02-ef6c-11e5-9220-8d3243a173e0.png)
Alors que le moteur est debout, je suis connecté à son interface native (de même pour le moteur `arii`).

Parfois une erreur Symfony se cache sur le côté droit de la page, impossible d'en lire le contenu car elle "dépop" quand on clique, ça parle d'entité ... je ne pense pas que cela aide beaucoup.

**Comment by AxelANGENAULT** [comment]
Bonjour,

J'ai refait le test à partir d'une VM sans les modifications du client-utilisateur, 
j’obtiens le même résultat.

Ci-dessus l'historique du terminal :
 ```
arii@Arii-2016:~/Symfony$ history | tail -n 9
 1999  exit # fin ssh avant compressions Arii64.zip
 2000  cd ~/Symfony/src/Arii/JOCBundle/
 2001  git pull
 2002  cd ~/Symfony/
 2003  php app/console doctrine:schema:update --force
 2004  rm -Rf ~/Symfony/app/cache/*
 2005  rm -Rf ~/Symfony/app/logs/*.log
 2006  sudo service apache2 restart
 2007  history | tail -n 9
```

Et toujours les mêmes les mêmes remontée en mode debug, ai-je loupé quelque chose ?
( Je ne trouve pas mon bonheur dans le dev.log )

J'ai également une question :
Pourquoi les moteurs ne seraient-ils pas déclarés dans AdminBundle pour être utilisés ensuite dans le JOCBundle ?

**Comment by AriiPortal** [comment]
Problème de résolution de nom au niveau du serveur OJS. 
Une bonne pratique est d'indiquer l'adresse d'écoute (ip_address="IP") dans le fichier scheduler.xml
